### PR TITLE
activeItem.html undefined

### PR DESCRIPTION
**Pull request by TMK04**
This PR assigns html to activeItem when looping over nodes/nodelists.

Previously, rendering activeItem would check for img | sources | iframe | html.
HTML Nodes don't have those properties, so the fallback case "activeItem.html" would render undefined.

### CODE REVIEW

**Comment by henrygd** [comment]
Thanks, might be a few days before I can look at this and make a new release

**Comment by henrygd** [comment]
Can you give me some more info on what what situation you're in where this is necessary?

HTML elements don't have those properties, but they can be provided to the library via data attributes. Or you should be able to do something like this:

```js
bp.open({
  el: e.currentTarget,
  items: [...elements].map(element => ({element, html: element.outerHTML}))
})
```

Let me know if I'm missing the point here.

I agree that opening `undefined` as HTML is confusing, but maybe it would be better to throw an error at that point instead of falling back to opening the outerHTML of `element`. That would also be confusing to a user if they're trying to open an image but use `image` as the property name instead of `img`, for example.

**Comment by TMK04** [comment]
Just realized, this PR is a different issue than this one.

Main reason: It's declarative for a user to pass in `{ items: document.querySelector("selector") }` & expect the element to be displayed as-is.
It's also better for nodelists cuz bigger-picture's already looping over the nodes.

If you reject this change then, like you said, throw an error. The docs will also need to explain & mandate the use of `data-img|sources|iframe|html`; The docs now convey that data- attributes are compatible, not mandatory. In any case, `undefined` doesn't explain very well.

As for `image` (or some other prop), the only way they would be confusing would be if a user passes in both the element & `data-image`/`{ image }`, for which typings & docs would let them know to use `img`

**Comment by henrygd** [comment]
Okay. I like the getter idea but how about just putting the fallback right in [line 337](https://github.com/henrygd/bigger-picture/blob/51d48fd5281225c8a96c33283c41714704c2ac06/src/bigger-picture.svelte#L337) instead?

`{@html activeItem.html ?? activeItem.element.outerHTML}`

**Comment by TMK04** [comment]
[af50591](https://github.com/henrygd/bigger-picture/pull/37/commits/af505915f7306323c02147f57d48e74588fec690)
Letting bigger-picture know that html exists takes advantage of lines [68](https://github.com/TMK04/bigger-picture/blob/85566334ff6abf4d3931e5330012ef92399adb96/src/bigger-picture.svelte#L68) & [237](https://github.com/TMK04/bigger-picture/blob/85566334ff6abf4d3931e5330012ef92399adb96/src/bigger-picture.svelte#L237)

**Comment by henrygd** [comment]
You're right, we should make it work with `activeItemIsHtml` but I think we'll still run into issues with the way it currently checks (`activeItem.hasOwnProperty('html')`).

Let's do it the way I suggested above -- `{@html activeItem.html ?? activeItem.element.outerHTML}` -- and after that I'll update the way it checks if the active item is html.

So the only thing we need changed in this pr is line 337.

**Pull request merged**
